### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by crisan211** [Hary309/hry-core#2]
Hello, 
when i compile the plugin and test ingame, the game crash. I saw that the size of .Dll file, is different from the one you have compiled. 
Could you explain me how to compile the code correctly? 
Thank you

**Comment by Hary309** [comment]
Can you show the `game.crash.txt`?

**Comment by crisan211** [comment]
Fixed the error.. Are you going to make a tutorial like showing how get a pattern for the hook?

**Comment by Hary309** [comment]
You just have to copy the byte code (hex values) that you want to hook and just copy it to `hry::pattern`.
If you want to make it work for more than one version of the game, you have to replace bytes that change between game patches/update with `?`. 

Example: https://github.com/Hary309/hry-sic/blob/master/src/Hooks/CameraHook.cpp#L37

btw. if you just want to develop a plugin that is based on hry-core I strongly suggest using the [compiled version](https://github.com/Hary309/hry-core/releases/tag/1.0.1).
